services:

  postgres:
    image: postgres:16
    container_name: ecommerce-postgres

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10


  user-service:
    build:
      context: .
      dockerfile: user_services/Dockerfile

    container_name: ecommerce-user-service

    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/ecommerce_user_db
      API_TOKEN: ${API_TOKEN}

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "5002:5002"


  product-service:
    build:
      context: .
      dockerfile: product_services/Dockerfile

    container_name: ecommerce-product-service

    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/ecommerce_product_db
      API_TOKEN: ${API_TOKEN}

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "5001:5001"


  order-service:
    build:
      context: .
      dockerfile: order_service/Dockerfile

    container_name: ecommerce-order-service

    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/ecommerce_order_db
      API_TOKEN: ${API_TOKEN}

      USER_SERVICE_URL: http://user-service:5002
      PRODUCT_SERVICE_URL: http://product-service:5001

    depends_on:
      postgres:
        condition: service_healthy

      user-service:
        condition: service_started

      product-service:
        condition: service_started

    ports:
      - "5003:5003"


  api-gateway:
    build:
      context: .
      dockerfile: api_gateway/Dockerfile

    container_name: ecommerce-api-gateway

    environment:
      PRODUCT_SERVICE_URL: http://product-service:5001
      USER_SERVICE_URL: http://user-service:5002
      ORDER_SERVICE_URL: http://order-service:5003

    depends_on:
      user-service:
        condition: service_started

      product-service:
        condition: service_started

      order-service:
        condition: service_started

    ports:
      - "5000:5000"


  frontend:
    build:
      context: .
      dockerfile: front_end/Dockerfile

    container_name: ecommerce-frontend

    depends_on:
      api-gateway:
        condition: service_started

    ports:
      - "5500:5500"


volumes:
  postgres_data:
